BOARD_TAG = leonardo
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = nextion Wire SPI SD SoftwareSerial screenInterface cabinetShared
AVR_TOOLS_DIR = /usr
ARDUINO_SKETCHBOOK = ../
include /usr/share/arduino/Arduino.mk
